### ISSUE TITLE
psmove_count_connected() finds controller even when it's not connected

### ISSUE THREAD

**Issue by cboulay** [nitsch/psmove-pair-win#3] opened 2015-04-01 18:48 UTC
This issue is probably fixed in the psmoveapi, but I think it's Windows-specific, and maybe even Windows 8-specific, so I'll try posting it here first.

When the controller is paired using psmove-pair-win, psmove_count_connected() still identifies and counts the controller even when it is not currently connected. I have to right-click on the device in the "Devices and Printers" windows and choose "Remove Device". This effectively unpairs the device and it can no longer be connected by pressing the PSMove button.

The obvious solution is to get the psmoveapi to try to communicate with the controller before it enumerates it, but I wonder if there's something specific to the way we're doing the pairing here.

**Comment by cboulay** [comment] 2015-04-02 13:55
Just to clarify above, I mean when it is not connected by BT or USB.
Anyway, I removed the controller then re-added it using psmove-pair-win and it is no longer behaving like that. It's a bit frustrating how non-deterministic this is. But that's why we get paid the big bucks.

**Comment by nitsch** [comment] 2015-04-02 16:42
> When the controller is paired using psmove-pair-win,
> psmove_count_connected() still identifies and counts the controller
> even when it is not currently connected. I have to right-click on the
> device in the "Devices and Printers" windows and choose "Remove
> Device". This effectively unpairs the device and it can no longer be
> connected by pressing the PSMove button.

Sounds like a similar issue with the Move that I could reproduce on
Windows 7:

  https://groups.google.com/d/topic/psmove/njN8hoIaWKM

Since this tool here has actually nothing to do with the psmoveapi, I am
tempted to just close this issue. Also, if it really is related to the
issue linked above, this is probably not even an issue in psmoveapi
(apart from the crashes that probably result from relying on Windows to
tell you the truth about the device/connection status) but something
strange in the operating system itself.

> The obvious solution is to get the psmoveapi to try to communicate
> with the controller before it enumerates it ...

I currently have no idea how to properly fix the actual problem. That
would probably require some digging into Windows internals. Adding these
extra checks instead of relying on Windows seems to be the only way
around it at the moment, I am afraid.

> ... but I wonder if there's something specific to the way we're doing
> the pairing here.

I do not think so. This tool just does what you would otherwise have to
do manually. Connecting the Move on Windows always worked from the very
beginning. It just was a real pain to get the timing right and usually
required _lots_ of retries.

> It's a bit frustrating how non-deterministic this is. But that's why 
> we get paid the big bucks.

We are? Damn it, I knew I did something wrong doing this in my spare
time. ;)

**Comment by cboulay** [comment] 2015-04-02 16:49
Thanks for clearing that up. I agree there's nothing to be done here. Please close the issue.

**Closed as completed** 2015-04-05 22:02 UTC
